<?php

namespace BusBundle\Repository;

/**
 * BusDepartureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BusDepartureRepository extends \Doctrine\ORM\EntityRepository
{
    public function getNextDepartures($busStopId, $type)
    {
        $departures = $this->getEntityManager()
            ->createQuery(
                'SELECT bd FROM BusBundle:BusDeparture bd
                 JOIN bd.busStop bs
                 WHERE bs.id = :busStopId AND bd.departureType = :departureType
                 ORDER BY bd.departureTime ASC'
            )
            ->setParameters(array(
                'busStopId' => $busStopId,
                'departureType' => $type
            ))
            ->getResult();

        $outDepartures = array();

        foreach ($departures as $departure) {
            $time = $departure->getDepartureTime();
            $time = $time->format('H:i');
            if ($time > date('H:i')) {
                $outDepartures[] = array(
                    'departureTime' => $time,
                    'endpoint' => $departure->getBusLine()->getEndpoint(),
                    'busLine' => $departure->getBusLine()->getName()
                );
            }
        }

        return $outDepartures;

    }
}
