<?php

namespace BusBundle\Repository;

/**
 * BusLineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BusLineRepository extends \Doctrine\ORM\EntityRepository
{
}
